name: Build APK
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build APK (Auto-confirm)
        run: |
          # Команда 'yes' будет бесконечно слать букву 'y', 
          # пока flet build apk будет задавать вопросы про установку Flutter
          yes y | flet build apk
          
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ze-conventor-app
          path: build/apk/*.apk
